config/routes.rb
Rails.application.routes.draw do
  get 'ponyfy/index'

  root :to => redirect('/ponies')
  resources :ponies


end

app/models/pony.rb
class Pony < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ponies_controller.rb
class PoniesController < ApplicationController
  before_action :set_pony, only: [:show, :edit, :update, :destroy]

  # GET /ponies
  # GET /ponies.json
  def index
    @ponies = Pony.all
  end

  # GET /ponies/1
  # GET /ponies/1.json
  def show
  end

  # GET /ponies/new
  def new
    @pony = Pony.new
  end

  # GET /ponies/1/edit
  def edit
  end

  # POST /ponies
  # POST /ponies.json
  def create
    @pony = Pony.new(pony_params)

    respond_to do |format|
      if @pony.save
        format.html { redirect_to @pony, notice: 'Pony was successfully created.' }
        format.json { render :show, status: :created, location: @pony }
      else
        format.html { render :new }
        format.json { render json: @pony.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ponies/1
  # PATCH/PUT /ponies/1.json
  def update
    respond_to do |format|
      if @pony.update(pony_params)
        format.html { redirect_to @pony, notice: 'Pony was successfully updated.' }
        format.json { render :show, status: :ok, location: @pony }
      else
        format.html { render :edit }
        format.json { render json: @pony.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ponies/1
  # DELETE /ponies/1.json
  def destroy
    @pony.destroy
    respond_to do |format|
      format.html { redirect_to ponies_url, notice: 'Pony was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pony
      @pony = Pony.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pony_params
      params.require(:pony).permit(:name, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ponies_helper.rb
module PoniesHelper
end

app/helpers/ponyfy_helper.rb
module PonyfyHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ponyfyme</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.js"></script>
	<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.1/themes/base/jquery-ui.css"/>

  <%= csrf_meta_tags %>
</head>
<bod>

<h1>Ponyfy Me</h1>

<%= yield %>

</body>
</html>

app/views/ponies/_form.html.erb
<%= form_for @pony, :html => {:multipart => true} do |f| %>
  <% if @pony.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pony.errors.count, "error") %> prohibited this pony from being saved:</h2>

      <ul>
      <% @pony.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ponies/edit.html.erb
<h1>Editing pony</h1>

<%= render 'form' %>

<%= link_to 'Show', @pony %> |
<%= link_to 'Back', ponies_path %>

app/views/ponies/index.html.erb
<div class="row" id="listPonies">
  <% @ponies.each do |pony| %>
    <div class="col-lg-3 pony">
      <a href="/ponies/<%= pony.id %>">
        <%= image_tag(pony.picture_url, :width => 600) if pony.picture.present? %>
        <h3><%= pony.name %></h3>
      </a>
    </div>
  <% end %>
</div>
<%= link_to 'New Pony', new_pony_path %>

app/views/ponies/new.html.erb
<h1>New pony</h1>

<%= render 'form' %>

<%= link_to 'Back', ponies_path %>

app/views/ponies/show.html.erb
<%= javascript_include_tag 'pixastic.custom' %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pony.name %>
</p>

<div id="modifyMyPony">
	<img src="<%= asset_path "ponies/pony_2.png" %>" id="realPony" />
  <%= image_tag(@pony.picture_url, :width => 300, :id => 'myPonyFace') if @pony.picture.present? %>
</div>

<%= link_to 'Edit', edit_pony_path(@pony) %> |
<%= link_to 'Back', ponies_path %>

<div class="optionsAjustColors">

	<div>
		Red: <input type="text" id="value-red" value="0" />
	</div>
	<div id="slider-red" class="ui-slider" style="width:150px;margin-top:5px;margin-bottom:5px;">
		<a href="#" style="outline:none;border:none;">
			<div class="ui-slider-handle" style="left: 57px;"></div>
		</a>
		<div class="ui-slider-range"></div>
	</div>

	<div>
		Green:
		<input type="text" id="value-green" value="0" />
	</div>
	<div id="slider-green" class="ui-slider" style="width:150px;margin-top:5px;margin-bottom:5px;">
		<a href="#" style="outline:none;border:none;">
			<div class="ui-slider-handle" style="left: 69px;"></div>
		</a>
		<div class="ui-slider-range"></div>
	</div>

	<div>
		Blue:
		<input type="text" id="value-blue" value="0" />
	</div>
	<div id="slider-blue" class="ui-slider" style="width:150px;margin-top:5px;margin-bottom:5px;">
		<a href="#" style="outline:none;border:none;">
			<div class="ui-slider-handle" style="left: 69px;"></div>
		</a>
		<div class="ui-slider-range"></div>
	</div>

	<input type="button" onclick="ajustColors();" value="Adjust colors" />
	<input type="button" onclick="resetColors();" value="Reset"><br>
</div>

<!--<div id="createPony">

	<img src="<%= asset_path "ponies/pony_2.png"%>" />

</div>-->



<script type="text/javascript">

	function ajustColors() {

		$("#myPonyFace").pixastic("coloradjust", {
			red: $('#value-red').val(),
			blue: $('#value-blue').val(),
			green: $('#value-green').val(),
		});

	}

	$(document).ready(function(e) {

		$("#slider-red").slider({
			slide: function() {
				$("#value-red").val((($("#slider-red").slider("value") / 100 * 2) - 1).toFixed(2));
				}, value : 50
		}).slider("moveTo", 75);
		$("#slider-green").slider({
				slide: function() {
					$("#value-green").val((($("#slider-green").slider("value") / 100 * 2) - 1).toFixed(2));
				}, value : 50
		}).slider("moveTo", 50);
		$("#slider-blue").slider({
				slide: function() {
					$("#value-blue").val((($("#slider-blue").slider("value") / 100 * 2) - 1).toFixed(2));
				}, value : 50
		}).slider("moveTo", 50);

		$(function() {

			var $img = $("#realPony");
			var imgPos = $img.offset();
			console.log(imgPos);

		    $( "#myPonyFace" ).draggable({ containment: 'parent' });
		    $( "#myPonyFace" ).resizeable();
		    // $( "#droppable" ).droppable({
		    //   drop: function( event, ui ) {
		    //     $( this )
		    //       .addClass( "ui-state-highlight" )
		    //       .find( "p" )
		    //         .html( "Dropped!" );
		    //   }
		    // });
		  });

	});

--></script>